### ISSUE TITLE
PCE-CD BIOS is incorrect.

### ISSUE THREAD

**Issue by birdybro** [MAME-GETTER/MiSTer_BIOS_SCRIPTS#12]
![HDoRS8eXDf](https://user-images.githubusercontent.com/16388068/112782151-9a22a800-9009-11eb-8efb-8036d47d9c27.png)

https://github.com/MiSTer-devel/TurboGrafx16_MiSTer#cd-rom-games

```Attention about US BIOS: MiSTer requires original dump of US BIOS to work properly. It needs to be of 262144 bytes. If you can read copyright string at the end of US BIOS file, then it's not correct dump! It's already pre-swapped for emulators. While it will work on MiSTer, some CD games will refuse to start. Correct US BIOS file is when copyright string is not readable.```

I think the correct BIOS should be this --> [BIOS] TurboGrafx CD Super CD-ROM2 System V3.01 (USA).pce - CRC32 = 9759A20D - MD5 = 98D43A097A165B03DF170FD5C2AD2C2F

It's easily found on General Emulation Wiki.

Source of problem: https://misterfpga.org/viewtopic.php?p=21921#p21921

**Comment by MAME-GETTER** [comment]
BIOS pack has been updated with a new TG16 CD Bios zip. 

Super CD 3.1.pce md5sum 98d43a097a165b03df170fd5c2ad2c2f  

@birdybro Thank you for this bug filing.
