### ISSUE TITLE
URL for internet archive is incorrect

### ISSUE THREAD

**Issue by nightkill9988** [MAME-GETTER/MiSTer_BIOS_SCRIPTS#13]
The URL for the BIOS files is incorrect. current example in script is:
'.../download/mi-ster-console-bios-pack/MiSTer_Console_BIOS_PACK.zip/NeoGeo.zip'

this should be updated to:
'.../download/mi-ster-console-bios-pack/MiSTer_Console_BIOS_PACK.zip/MiSTer_Console_BIOS_PACK/NeoGeo.zip'

It appears that  MiSTer_Console_BIOS_PACK.zip was updated on 3/29/2021 which might have lead to this change

**Comment by MAME-GETTER** [comment]
This has already been fixed. Remove the current bio and rerun the the
BIOS-GETTER or update_all.sh

**Comment by MAME-GETTER** [comment]
This issue is already been corrected. Please remove the BIOS and rerun BIOS-GETTER or update all

**Comment by nightkill9988** [comment]
This was on a new build and first time running update_all.sh and BIOS-GETTER with nothing else installed on the SD card. The error was that the archive/file could not be found for every BIOS that is included in this pack.

**Comment by nightkill9988** [comment]
This is a new build of mister and the first time running update_all or BIOS-GETTER. The error received for all BIOS downloads is:

STARTING BIOS RETRIVAL FOR: Astrocade

Downloading https://archive.org/download/mi-ster-console-bios-pack/MiSTer_Console_BIOS_PACK.zip/Astrocade.zip
Archive:  /media/fat/BIOS/Astrocade.zip

  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
note:  /media/fat/BIOS/Astrocade.zip may be a plain executable, not an archive
unzip:  cannot find zipfile directory in one of /media/fat/BIOS/Astrocade.zip or
        /media/fat/BIOS/Astrocade.zip.zip, and cannot find /media/fat/BIOS/Astrocade.zip.ZIP, period.
cp: cannot stat '/media/fat/BIOS/Astrocade/Bally Professional Arcade, Astrocade '\''3159'\'' BIOS (1978)(Bally Mfg. Corp.).bin': No such file or directory

Just tested again on a clean SD card with update_all.sh and received the same error. Going directly to the URL on a desktop results in a 0kb file download. The actual URL path for the BIOS in this message is:
https://archive.org/download/mi-ster-console-bios-pack/MiSTer_Console_BIOS_PACK.zip**/MiSTer_Console_BIOS_PACK/**Astrocade.zip

**Comment by MAME-GETTER** [comment]
testing

**Comment by nightkill9988** [comment]
Tested and it works. Thank you for repacking the BOIS pack.

**Comment by MAME-GETTER** [comment]
@nightkill9988 Thank you for reporting and taking time explain the issue. The incorrect packing was an oversight. Its users like you who help make these scripts great.
