### ISSUE TITLE
Wonderswan BIOS update

### ISSUE THREAD

**Issue by birdybro** [MAME-GETTER/MiSTer_BIOS_SCRIPTS#14]
The WonderSwan core is released and as such the script should probably include the correct BIOS files.

boot.rom = crc32 - 7F35F890
boot1.rom = crc32 - CB06D9C3

**Comment by MAME-GETTER** [comment]
Archive.org is experiencing issues with uploads currently. 

Will have the file up their once the issue is resolved.
