### ISSUE TITLE
Option for secondary /games location (or per console location)

### ISSUE THREAD

**Issue by edru** [MAME-GETTER/MiSTer_BIOS_SCRIPTS#2]
I have all ROMs on the main SD card, but place all BIN/ISO files on an external HDD. Would there be a way to add 2 games directories? Or perhaps declare, per console, where they are located?

**Comment by theypsilon** [comment]
Yes, you can set:
`GAMESDIR="/media/usb0/games/`
in your "update_bios-getter.ini"

And the same with BIOSDIR="/media/usb0/BIOS"

**Comment by theypsilon** [comment]
It looks doable, having a GAMES2DIR and fallback to it if system is not found in GAMESDIR.

**Comment by theypsilon** [comment]
This is no longer needed since we have gamesdir auto detection now (same algorithm as Main_MiSTer).
