### ISSUE TITLE
BSX BIOS

### ISSUE THREAD

**Issue by birdybro** [MAME-GETTER/MiSTer_BIOS_SCRIPTS#8]
I am failing at scripting or something, too unfamiliar. My draft doesn't work and neither did hours of trying to fix it.

Just going to submit this as an issue since as usual, I'm in over my head :P

**Comment by ajgowans** [comment]
Ideally the BIOS to get would be the English translated "BS-X no drm bios"

**Comment by MAME-GETTER** [comment]
This has been implement by theypsilon. He used all 4 bios files. See /media/fat/BIOS for the files used. Closing

**Comment by theypsilon** [comment]
Default installed is english no drm.
