### ISSUE TITLE
Atari Jaguar BIOS

### ISSUE THREAD

**Issue by ajgowans** [MAME-GETTER/MiSTer_BIOS_SCRIPTS#9]
Would it be possible if there is a "Jaguar" folder on the SD to add the Jaguar BIOS to there?

"The BIOS file (usually "jagboot.rom") should be renamed to boot.rom, then copied into the Jaguar folder on the SD card."
https://github.com/ElectronAsh/Jaguar_MiSTer_new

Ash is looking to work more on the core and hopefully has some other devs interested in helping also.

**Comment by MAME-GETTER** [comment]
When the core is official will add the bios.
